#!/bin/sh

# PATH
export PATH=$PATH:$HOME/.local/bin:$HOME/.local/bin/shell:$HOME/.local/share/platformio/penv/bin:$HOME/.local/share/fzy-lua-native

# Default programs
export EDITOR="nvim"
export TERMINAL="kitty"
export BROWSER="brave"

# Clean Up
# XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CACHE_HOME="$HOME/.cache"
export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"
export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export ZSH="$ZDOTDIR/oh-my-zsh"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export GOPATH="$XDG_DATA_HOME/go"
export HISTFILE="$XDG_STATE_HOME/zsh/history"
export PYTHON_HISTORY="$XDG_STATE_HOME/python/history"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export PLATFORMIO_CORE_DIR="$XDG_DATA_HOME/platformio"

# start x
if [ -z "$DISPLAY" ] && [ "$XDG_VTNR" = 1 ]; then
	exec startx
fi
